@startuml 精算する

usecase 精算する

actor ユーザー
boundary ショッピングカートの編集ページ
control すべての住所を取得する
entity 住所
control 表示する
boundary 配送先住所ページ
control 配送先住所を設定する
entity 注文

ユーザー --> ショッピングカートの編集ページ : 精算ボタンをクリック
ユーザー --> 配送先住所ページ : 住所を選択する
ショッピングカートの編集ページ --> すべての住所を取得する
すべての住所を取得する --> 住所
すべての住所を取得する  --> 表示する
表示する --> 配送先住所ページ
配送先住所ページ --> 配送先住所を設定する
配送先住所を設定する --> 注文

@enduml
